### ISSUE TITLE
build on ubuntu 13.10 and 14.04

### ISSUE THREAD

**Issue by prohaska** [Tokutek/mariadb-5.5#68]
link mysqld

```
Linking CXX executable mysqld
cd /home/rfp/ma5538/build/sql && /usr/bin/cmake -E cmake_link_script CMakeFiles/mysqld.dir/link.txt --verbose=1
/usr/bin/c++   -Wall  -fPIC -Wno-unused-parameter -fno-implicit-templates -fno-exceptions -fno-rtti -g -DENABLED_DEBUG_SYNC -ggdb3 -DSAFE_MUTEX -DSAFEMALLOC  -Wall -Wextra -Wunused -Wwrite-strings -Wno-strict-aliasing -Wno-missing-field-initializers -Wno-unused-parameter -Woverloaded-virtual    -Wl,--export-dynamic CMakeFiles/mysqld.dir/main.cc.o  -o mysqld  ../toku_backup/libHotBackupCommunity.so libsql.a ../storage/maria/libaria.a ../storage/myisam/libmyisam.a ../storage/myisammrg/libmyisammrg.a ../storage/heap/libheap.a ../storage/xtradb/libxtradb.a -laio ../storage/perfschema/libperfschema.a ../storage/csv/libcsv.a libpartition.a ../mysys/libmysys.a ../dbug/libdbug.a ../mysys/libmysys.a ../dbug/libdbug.a -lz -lm ../strings/libstrings.a ../vio/libvio.a ../regex/libregex.a .././extra/jemalloc/build/lib/libjemalloc_pic.a -lcrypt -ldl -lpthread -Wl,-rpath,/home/rfp/ma5538/build/toku_backup: 
libsql.a(sql_backup.cc.o): In function `sql_backups(char const*, char const*, THD*)':
/home/rfp/ma5538/mariadb-5.5.38/sql/sql_backup.cc:57: undefined reference to `tokubackup_create_backup'
libsql.a(sql_backup.cc.o): In function `sql_backuLinking CXX executable mysqld
cd /home/rfp/ma5538/build/sql && /usr/bin/cmake -E cmake_link_script CMakeFiles/mysqld.dir/link.txt --verbose=1
/usr/bin/c++   -Wall  -fPIC -Wno-unused-parameter -fno-implicit-templates -fno-exceptions -fno-rtti -g -DENABLED_DEBUG_SYNC -ggdb3 -DSAFE_MUTEX -DSAFEMALLOC  -Wall -Wextra -Wunused -Wwrite-strings -Wno-strict-aliasing -Wno-missing-field-initializers -Wno-unused-parameter -Woverloaded-virtual    -Wl,--export-dynamic CMakeFiles/mysqld.dir/main.cc.o  -o mysqld  ../toku_backup/libHotBackupCommunity.so libsql.a ../storage/maria/libaria.a ../storage/myisam/libmyisam.a ../storage/myisammrg/libmyisammrg.a ../storage/heap/libheap.a ../storage/xtradb/libxtradb.a -laio ../storage/perfschema/libperfschema.a ../storage/csv/libcsv.a libpartition.a ../mysys/libmysys.a ../dbug/libdbug.a ../mysys/libmysys.a ../dbug/libdbug.a -lz -lm ../strings/libstrings.a ../vio/libvio.a ../regex/libregex.a .././extra/jemalloc/build/lib/libjemalloc_pic.a -lcrypt -ldl -lpthread -Wl,-rpath,/home/rfp/ma5538/build/toku_backup: 
libsql.a(sql_backup.cc.o): In function `sql_backups(char const*, char const*, THD*)':
/home/rfp/ma5538/mariadb-5.5.38/sql/sql_backup.cc:57: undefined reference to `tokubackup_create_backup'
libsql.a(sql_backup.cc.o): In function `sql_backup_throttle(unsigned long)':
/home/rfp/ma5538/mariadb-5.5.38/sql/sql_backup.cc:63: undefined reference to `tokubackup_throttle_backup'
libsql.a(sql_backup.cc.o): In function `__static_initialization_and_destruction_0':
/home/rfp/ma5538/mariadb-5.5.38/sql/sql_backup.cc:66: undefined reference to `tokubackup_version_string'
collect2: error: ld returned 1 exit statusLinking CXX executable mysqld
cd /home/rfp/ma5538/build/sql && /usr/bin/cmake -E cmake_link_script CMakeFiles/mysqld.dir/link.txt --verbose=1
/usr/bin/c++   -Wall  -fPIC -Wno-unused-parameter -fno-implicit-templates -fno-exceptions -fno-rtti -g -DENABLED_DEBUG_SYNC -ggdb3 -DSAFE_MUTEX -DSAFEMALLOC  -Wall -Wextra -Wunused -Wwrite-strings -Wno-strict-aliasing -Wno-missing-field-initializers -Wno-unused-parameter -Woverloaded-virtual    -Wl,--export-dynamic CMakeFiles/mysqld.dir/main.cc.o  -o mysqld  ../toku_backup/libHotBackupCommunity.so libsql.a ../storage/maria/libaria.a ../storage/myisam/libmyisam.a ../storage/myisammrg/libmyisammrg.a ../storage/heap/libheap.a ../storage/xtradb/libxtradb.a -laio ../storage/perfschema/libperfschema.a ../storage/csv/libcsv.a libpartition.a ../mysys/libmysys.a ../dbug/libdbug.a ../mysys/libmysys.a ../dbug/libdbug.a -lz -lm ../strings/libstrings.a ../vio/libvio.a ../regex/libregex.a .././extra/jemalloc/build/lib/libjemalloc_pic.a -lcrypt -ldl -lpthread -Wl,-rpath,/home/rfp/ma5538/build/toku_backup: 
libsql.a(sql_backup.cc.o): In function `sql_backups(char const*, char const*, THD*)':
/home/rfp/ma5538/mariadb-5.5.38/sql/sql_backup.cc:57: undefined reference to `tokubackup_create_backup'
libsql.a(sql_backup.cc.o): In function `sql_backup_throttle(unsigned long)':
/home/rfp/ma5538/mariadb-5.5.38/sql/sql_backup.cc:63: undefined reference to `tokubackup_throttle_backup'
libsql.a(sql_backup.cc.o): In function `__static_initialization_and_destruction_0':
/home/rfp/ma5538/mariadb-5.5.38/sql/sql_backup.cc:66: undefined reference to `tokubackup_version_string'
collect2: error: ld returned 1 exit statusp_throttle(unsigned long)':
/home/rfp/ma5538/mariadb-5.5.38/sql/sql_backup.cc:63: undefined reference to `tokubackup_throttle_backup'
libsql.a(sql_backup.cc.o): In function `__static_initialization_and_destruction_0':
/home/rfp/ma5538/mariadb-5.5.38/sql/sql_backup.cc:66: undefined reference to `tokubackup_version_string'
collect2: error: ld returned 1 exit status
```

link explain_filename-t

```
Linking CXX executable explain_filename-t
cd /home/rfp/ma5538/build/unittest/sql && /usr/bin/cmake -E cmake_link_script CMakeFiles/explain_filename-t.dir/link.txt --verbose=1
/usr/bin/c++   -Wall  -fPIC -Wno-unused-parameter -fno-implicit-templates -fno-exceptions -fno-rtti -g -DENABLED_DEBUG_SYNC -ggdb3 -DSAFE_MUTEX -DSAFEMALLOC  -Wall -Wextra -Wunused -Wwrite-strings -Wno-strict-aliasing -Wno-missing-field-initializers -Wno-unused-parameter -Woverloaded-virtual    CMakeFiles/explain_filename-t.dir/explain_filename-t.cc.o  -o explain_filename-t  ../../toku_backup/libHotBackupCommunity.so ../../sql/libsql.a ../mytap/libmytap.a ../../storage/maria/libaria.a ../../storage/myisam/libmyisam.a ../../storage/myisammrg/libmyisammrg.a ../../storage/heap/libheap.a ../../storage/xtradb/libxtradb.a -laio ../../storage/perfschema/libperfschema.a ../../storage/csv/libcsv.a ../../sql/libpartition.a ../../mysys/libmysys.a ../../dbug/libdbug.a ../../mysys/libmysys.a ../../dbug/libdbug.a -lz -lm ../../strings/libstrings.a ../../vio/libvio.a ../../regex/libregex.a ../.././extra/jemalloc/build/lib/libjemalloc_pic.a -lcrypt -ldl -lpthread -Wl,-rpath,/home/rfp/ma5538/build/toku_backup 
../../sql/libsql.a(sql_backup.cc.o): In function `sql_backups(char const*, char const*, THD*)':
/home/rfp/ma5538/mariadb-5.5.38/sql/sql_backup.cc:57: undefined reference to `tokubackup_create_backup'
../../sql/libsql.a(sql_backup.cc.o): In function `sql_backup_throttle(unsigned long)':
/home/rfp/ma5538/mariadb-5.5.38/sql/sql_backup.cc:63: undefined reference to `tokubackup_throttle_backup'
../../sql/libsql.a(sql_backup.cc.o): In function `__static_initialization_and_destruction_0':
/home/rfp/ma5538/mariadb-5.5.38/sql/sql_backup.cc:66: undefined reference to `tokubackup_version_string'
```
